### ISSUE TITLE
Add a line about actinia and mention presentations

### ISSUE THREAD

**Issue by veroandreo** [veroandreo/tgrass-foss4g2019#1]
We should add a line about actinia in the GRASS intro part of the TGRASS workshop at FOSS4G with a link to your talk(s) in the conference. What do you say @neteler?

**Comment by neteler** [comment]
Yes, good idea. Here a snippet:

Actinia (https://actinia.mundialis.de/; DOI: [10.5281/zenodo.2631917](https://doi.org/10.5281/zenodo.2631917)) is an open source REST API for scalable, distributed, high performance processing of geographical data that uses GRASS GIS for computational tasks. Core functionality includes the processing of single and time series of satellite images, of raster and vector data. Actinia is an OSGeo Community Project since 2019.

Actinia related FOSS4G talks:
- https://talks.2019.foss4g.org/bucharest/talk/GCNPMC/
- https://talks.2019.foss4g.org/bucharest/talk/U3DM9L/

**Comment by veroandreo** [comment]
Thanks! 

Added with lil modifications in https://github.com/veroandreo/tgrass-foss4g2019/commit/f78e6da9b1bb20a5623c7032b4e8425f709aa446

I will now check how the layout looks like and edit accordingly

Cheers
